version: 1.0.{build}

environment:
  nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

only_commits:
  message: /build-release/

build_script:
  - ps: npm run build:webapp:prod
  - ps: npm run build:win

branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

environment:
  GH_TOKEN:
    secure: D04x8djK8cRtoR47RIi3HC3FArLnefMpk368HefDJoVwEvYUilileOceRA6gkBZ7

skip_tags: true